version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          command: pip install .
          name: Install current package
      - python/save-cache
      - run:
          command: python -m pytest
          name: Test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Add Dokku to known_hosts
          command: ssh-keyscan -H vps1.angioi.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy to Dokku
          command: git push -f dokku@vps1.angioi.com:twst master

workflows:
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
